# Generated by Django 4.2.30 on 2026-09-29 21:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from the title.', max_length=220, unique=True)),
                ('author', models.CharField(default='Emoji Kitchen Team', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on the blog listing page.')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('reading_time', models.PositiveIntegerField(blank=True, help_text='Estimated reading time in minutes. Leave blank to auto-calculate from the content.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this post on the blog page.')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seo_title', models.CharField(blank=True, help_text='Falls back to the post title if left blank.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Falls back to the excerpt if left blank.', max_length=160)),
                ('focus_keyword_title', models.CharField(blank=True, help_text='Enter a keyword — validated against the SEO title in real time.', max_length=100)),
                ('focus_keyword_description', models.CharField(blank=True, help_text='Enter a keyword — validated against the meta description in real time.', max_length=100)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('meta_robots', models.CharField(choices=[('index, follow', 'Index, Follow'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=30)),
                ('og_title', models.CharField(blank=True, help_text='Falls back to the SEO title if left blank.', max_length=95)),
                ('og_description', models.CharField(blank=True, help_text='Falls back to the SEO description if left blank.', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Falls back to the featured image if left blank.', null=True, upload_to='blog/og/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='kitchen.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='kitchen.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
